# Uncomment the next line to define a global platform for your project
platform :ios, '13.2'

target 'No' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for No
  pod 'HGCircularSlider', '~> 2.0.0'

end
